print("Program staring.")
print("Estimate how many minutes you spend on programming...")
T1=int(input("A1_T1: "))
T2=int(input("A1_T2: "))
T3=int(input("A1_T3: "))
T4=int(input("A1_T4: "))
T5=int(input("A1_T5: "))
T6=int(input("A1_T6: "))
T7=int(input("A1_T7: "))
Total=T1+T2+T3+T4+T5+T6+T7
Average=Total/7
Average=round(Average,2)
print(f"In total you spend {Total} minutes on programming.")
print(f"Average per task was {Average}min and same rounded to the nearest integer {round(Average)} min.")
print("Program ending.")